name: ReleaseAction

on:
  release:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v2

    - name: "Release and Changelog Action"
      # https://github.com/TriPSs/conventional-changelog-action
      uses: TriPSs/conventional-changelog-action@v3.10.0
      with:
        git-message: "chore(release): {version}"
        git-user-email: changelog_bump@github.actions.com
        git-user-name: "ReleaseAndChangelog"
        github-token: "${{ secrets.TOKEN }}"
        output-file: ./jenkins/webapp01/CHANGELOG.md
        release-count: 50
        skip-commit: true
        skip-on-empty: false
        skip-version-file: true
