name: BumpAction

on:
  push:
    branches: [ main ]
    paths:
    - 'jenkins/webapp01/src/**'
    - 'jenkins/webapp01/dockerfile'
    - 'jenkins/webapp01/nginx/**'
    - '!jenkins/webapp01/package.json'
    - '!CHANGELOG.md'
    - '!jenkins/webapp01/k8s/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  changelog_prerelease:
    name: Bump and Update Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Get latest release
        id: get_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
          excludes: prerelease, draft
      - name: Update Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: "${{ secrets.TOKEN }}"
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          usernamesAsGithubLogins: true
          headerLabel: "# Changes since release ${{ steps.get_release.outputs.release }}"
          sinceTag:  ${{ steps.get_release.outputs.release }}
      - name: move Changelog
        run: |
             cat CHANGELOG.md jenkins/webapp01/CHANGELOG.md > CHANGELOG_NEW.md
             mv CHANGELOG_NEW.md jenkins/webapp01/CHANGELOG.md
             rm -f CHANGELOG.md
      - name: auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Changelog
          commit_user_name: "ChangeLogUpdate"
          commit_user_email: "changelog_bump@github.actions.com"
          file_pattern: jenkins/webapp01/CHANGELOG.md
      - name: "Version Bump Action"
        uses: TriPSs/conventional-changelog-action@v3.10.0
        with:
          git-message: "chore(bump): {version}"
          git-user-email: changelog_bump@github.actions.com
          git-user-name: "VersionBumpAndTag"
          github-token: "${{ secrets.TOKEN }}"
          output-file: false
          skip-commit: false
          skip-on-empty: false
          skip-version-file: false
          tag-prefix: ""
          version-file: ./jenkins/webapp01/package.json
