name: BumpActions

on:
  push:
    branches: [ main ]
    paths:
    - 'jenkins/webapp01/src/**'
    - 'jenkins/webapp01/dockerfile'
    - 'jenkins/webapp01/nginx/**'
    - '!jenkins/webapp01/package.json'
    - '!CHANGELOG.md'
    - '!jenkins/webapp01/k8s/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  bump:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v2

    - name: "Version Bump Action"
      # https://github.com/TriPSs/conventional-changelog-action
      uses: TriPSs/conventional-changelog-action@v3.10.0
      with:
        git-message: "chore(bump): {version}"
        git-user-email: changelog_bump@github.actions.com
        git-user-name: "VersionBumpAndTag"
        github-token: "${{ secrets.TOKEN }}"
        output-file: false
        skip-commit: false
        skip-on-empty: false
        skip-version-file: false
        tag-prefix: ""
        version-file: ./jenkins/webapp01/package.json
