name: BumpAction

on:
  push:
    branches: [ main ]
    paths:
    - 'jenkins/webapp01/src/**'
    - 'jenkins/webapp01/dockerfile'
    - 'jenkins/webapp01/nginx/**'
    - '!jenkins/webapp01/package.json'
    - '!CHANGELOG.md'
    - '!jenkins/webapp01/k8s/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  changelog_prerelease:
    name: Update Changelog For Prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Update Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: "${{ secrets.TOKEN }}"
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          unreleased: true
          addSections: '{"documentation":{"prefix":" **Documentation:**","labels":["documentation"]}}'
      - name: move Changelog
        run: mv -f CHANGELOG.md jenkins/webapp01/CHANGELOG.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Changelog
          commit_user_name: "ChangeLogUpdate"
          commit_user_email: "changelog_bump@github.actions.com"
          file_pattern: jenkins/webapp01/CHANGELOG.md
  bump:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v2

    - name: "Version Bump Action"
      # https://github.com/TriPSs/conventional-changelog-action
      uses: TriPSs/conventional-changelog-action@v3.10.0
      with:
        git-message: "chore(bump): {version}"
        git-user-email: changelog_bump@github.actions.com
        git-user-name: "VersionBumpAndTag"
        github-token: "${{ secrets.TOKEN }}"
        output-file: false
        skip-commit: false
        skip-on-empty: false
        skip-version-file: false
        tag-prefix: ""
        version-file: ./jenkins/webapp01/package.json
